### ISSUE TITLE
WTrigAdvanced won't compile on teensy 3.5

### ISSUE THREAD

**Issue by jackjaquejack** [sparkfun/WAV_Trigger#2]
Hi there. 

Im trying to control the wav trigger via serial communication on the teensy 3.5, but it won't compile. It will compile with the teensy 3.6, and other teensy boards.  does anyone know what I could do to fix this? The project is large and has various pin expansion chips, rgb screens already. The awesome wav trigger is the final piece in the project, so it would be nice to be able to get it to compile. I've checked that I have the correct libs installed, and as I say it compiles on other teensy boards. Any help would be appreciated. error messages to follow, thank you!

/Users/Home/Documents/Arduino/libraries/Metro/Metro.cpp:42:16: warning: extra tokens at end of #ifdef directive
  #ifdef NOCATCH-UP
                ^
In file included from /Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:32:0:
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/config/AltSoftSerial_Boards.h:136:2: error: #error "Please define your board timer and pins"
 #error "Please define your board timer and pins"
  ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp: In static member function 'static void AltSoftSerial::init(uint32_t)':
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:68:27: error: 'CONFIG_TIMER_NOPRESCALE' was not declared in this scope
   CONFIG_TIMER_NOPRESCALE();
                           ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:72:28: error: 'CONFIG_TIMER_PRESCALE_8' was not declared in this scope
    CONFIG_TIMER_PRESCALE_8();
                            ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:79:10: error: 'INPUT_CAPTURE_PIN' was not declared in this scope
  pinMode(INPUT_CAPTURE_PIN, INPUT_PULLUP);
          ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:80:15: error: 'OUTPUT_COMPARE_A_PIN' was not declared in this scope
  digitalWrite(OUTPUT_COMPARE_A_PIN, HIGH);
               ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:88:27: error: 'ENABLE_INT_INPUT_CAPTURE' was not declared in this scope
  ENABLE_INT_INPUT_CAPTURE();
                           ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp: In static member function 'static void AltSoftSerial::end()':
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:93:24: error: 'DISABLE_INT_COMPARE_B' was not declared in this scope
  DISABLE_INT_COMPARE_B();
                        ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:94:28: error: 'DISABLE_INT_INPUT_CAPTURE' was not declared in this scope
  DISABLE_INT_INPUT_CAPTURE();
                            ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:97:24: error: 'DISABLE_INT_COMPARE_A' was not declared in this scope
  DISABLE_INT_COMPARE_A();
                        ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp: In static member function 'static void AltSoftSerial::writeByte(uint8_t)':
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:122:24: error: 'ENABLE_INT_COMPARE_A' was not declared in this scope
   ENABLE_INT_COMPARE_A();
                        ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:123:22: error: 'CONFIG_MATCH_CLEAR' was not declared in this scope
   CONFIG_MATCH_CLEAR();
                      ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:124:33: error: 'GET_TIMER_COUNT' was not declared in this scope
   SET_COMPARE_A(GET_TIMER_COUNT() + 16);
                                 ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:124:39: error: 'SET_COMPARE_A' was not declared in this scope
   SET_COMPARE_A(GET_TIMER_COUNT() + 16);
                                       ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp: At global scope:
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:130:4: error: expected constructor, destructor, or type conversion before '(' token
 ISR(COMPARE_A_INTERRUPT)
    ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:43:16: warning: 'rx_byte' defined but not used [-Wunused-variable]
 static uint8_t rx_byte;
                ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:44:16: warning: 'rx_bit' defined but not used [-Wunused-variable]
 static uint8_t rx_bit = 0;
                ^
/Users/Home/Documents/Arduino/libraries/AltSoftSerial/AltSoftSerial.cpp:45:17: warning: 'rx_target' defined but not used [-Wunused-variable]
 static uint16_t rx_target;
                 ^
Multiple libraries were found for "Metro.h"
 Used: /Users/Home/Documents/Arduino/libraries/Metro
 Not used: /private/var/folders/lc/3yqb2gz925d1czhsmn2cnz4r0000gn/T/AppTranslocation/9FE4EA52-FF66-48F3-A1C6-21D8DF2A8493/d/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/Metro
Multiple libraries were found for "AltSoftSerial.h"
 Used: /Users/Home/Documents/Arduino/libraries/AltSoftSerial
 Not used: /Users/Home/Documents/Arduino/libraries/AltSoftSerial-master
 Not used: /private/var/folders/lc/3yqb2gz925d1czhsmn2cnz4r0000gn/T/AppTranslocation/9FE4EA52-FF66-48F3-A1C6-21D8DF2A8493/d/Teensyduino.app/Contents/Java/hardware/teensy/avr/libraries/AltSoftSerial
Error compiling for board Teensy 3.5.
